language: c
os: linux
dist: trusty
sudo: required


addons:
  apt:
    packages:
      - gcc-multilib

install:
  - CI_scripts/get_compiler.sh
  - CI_scripts/get_includes.sh

script: 
  - CI_scripts/compile.sh gamemode.pwn